name: Cargo Build

on:
  push:
#    branches:
#      - main  # Assuming your default branch is named 'main'
#  pull_request:
#    branches:
#      - main


jobs:
  build:

    runs-on: idf-rust-runner

    steps:
      - uses: actions/checkout@v4

      - name: Setup Envionment
        run: |
          echo "BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S)" >> $GITHUB_ENV
          echo "SHORT_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Create Config
        run: |
          echo "[advent-of-code-esp]" > advent-of-code-esp/cfg.toml
          echo "wifi_ssid = \"${{ secrets.WIFI_SSID }}\"" >> advent-of-code-esp/cfg.toml
          echo "wifi_psk = \"${{ secrets.WIFI_PSK }}\"" >> advent-of-code-esp/cfg.toml

      - name: Build
        run: |
          git config --global core.compression 0
          cd advent-of-code-esp
          cargo build

      - name: Flash Firmware
        run: |
          cd advent-of-code-esp
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.AOC_FLASHER_FLASH_SSH_KEY }}" > ~/.ssh/aoc_flasher
          chmod 400 ~/.ssh/aoc_flasher
          echo "aoc-flasher.walther.lan,192.168.11.90 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLOWjBTN5js7DHp09iQljZSR5ZNfHdfA/LtffjmAAPhznKvFfWgWmUaOFH8RkgdEVR5AwLxMgWR6f+UUFAgNXDs=" > ~/.ssh/known_hosts
          ssh -4 -i ~/.ssh/aoc_flasher admin@192.168.11.90 'rm -rf ~/advent-of-code-esp'
          scp -4 -i ~/.ssh/aoc_flasher target/xtensa-esp32s3-espidf/debug/advent-of-code-esp admin@192.168.11.90:~/
          ssh -4 -i ~/.ssh/aoc_flasher admin@192.168.11.90 '/home/admin/.cargo/bin/espflash flash -p /dev/ttyACM0 ~/advent-of-code-esp'
          ssh -4 -i ~/.ssh/aoc_flasher admin@192.168.11.90 '/home/admin/.cargo/bin/espflash flash -p /dev/ttyACM1 ~/advent-of-code-esp'
          ssh -4 -i ~/.ssh/aoc_flasher admin@192.168.11.90 '/home/admin/.cargo/bin/espflash flash -p /dev/ttyACM2 ~/advent-of-code-esp'